###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "fakedDoctorsID",
  "startPoint": "2021-07-09T22:30:00.000Z"
}

###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "fakedDoctorsID2",
  "startPoint": "2021-07-19T21:30:00.000Z"
}

###
PUT http://localhost:4000/appointment/60e6d73abb3ff2412853dddd/
Content-Type: application/json

{
   "patient": "fakedPatientID3",
 "appointmentStatus": "SCHEDULED"
}
###
GET http://localhost:4000/appointment/60e6d6b707b555088cc57441

###
DELETE http://localhost:4000/appointment/60e6d5e1abdfe318a8359777