POST http://localhost:4000/doctor/
Content-Type: application/json

{
  "username": "testRadiologist4",
  "password": "1234",
  "name": "Max Musterman",
  "area_of_expertise": "RADIOLOGIST",
  "languages": ["GERMAN","ENGLISH"],
  "special_facilities": ["PARKING","WHEELCHAIR"]
}

###

POST http://localhost:4000/doctor/
Content-Type: application/json

{
"username": "testRadiologist522",
"password": "1234",
"name": "tim",
  "last_name": "tucker",
"area_of_expertise": "RADIOLOGIST",
"languages": ["FRENCH","ENGLISH"],
"special_facilities": ["PARKING"]
}

###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60e70bc72c79d33ed899b25f",
  "startPoint": "2021-07-09T22:30:00.000Z"
}
###
POST http://localhost:4000/appointment
Content-Type: application/json

{
"doctor": "60e70bc72c79d33ed899b25f",
"startPoint": "2021-07-09T23:30:00.000Z"
}

###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60e70bc72c79d33ed899b25f",
  "startPoint": "2021-07-09T21:30:00.000Z"
}
###
###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60e70bc72c79d33ed899b25f",
  "startPoint": "2021-07-09T20:30:00.000Z"
}

###
GET http://localhost:4000/appointment/
Content-Type: application/json

{
  "profession": "RADIOLOGIST",
  "languages": ["ENGLISH"],
  "facilities": ["PARKING"],
  "startpoint": "2021-07-09T10:30:00.000Z",
  "endpoint": "2021-07-09T23:30:00.000Z"

}

###

PUT http://localhost:4000/appointment/60e70be52c79d33ed899b264/
Content-Type: application/json

{
  "appointmentStatus": "SUCCESSFUL"
}

###
GET http://localhost:4000/appointment/doctor/60e70bc72c79d33ed899b25f
###

POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60e70bc72c79d33ed899b25f",
  "patient": "60e6bcc4e9f26d8dcca6f331",
  "startPoint": "2021-07-09T20:30:00.000Z"
}

###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60e70bc72c79d33ed899b25f",
  "patient": "60e6bcc4e9f26d8dcca6f331",
  "startPoint": "2021-07-20T20:30:00.000Z"
}

###

GET http://localhost:4000/appointment/patient/60e6bcc4e9f26d8dcca6f331

###
POST http://localhost:4000/appointment
Content-Type: application/json

{
  "doctor": "60f02fb877b8151174bbd394",
  "patient": "60e6bcc4e9f26d8dcca6f331",
  "startPoint": "2021-07-27T20:30:00.000Z"
}
###
GET http://localhost:4000/doctor